Repository Jejudo-Ticket/server, pull requests merged in 2025-07, with the labels that each got.

#8 feat: 초기 엔티티 설계 및 매핑
  backend_set/.idea/uiDesigner.xml
  backend_set/src/main/java/org/funding/ChatMessage/vo/ChatMessageVO.java
  backend_set/src/main/java/org/funding/Image/vo/ImageVO.java
  backend_set/src/main/java/org/funding/Image/vo/enumType/ImageType.java
  backend_set/src/main/java/org/funding/InterestingKeyword/vo/InterestingKeywordVO.java
  backend_set/src/main/java/org/funding/badge/vo/BadgeVO.java
  backend_set/src/main/java/org/funding/comment/vo/CommentVO.java
  backend_set/src/main/java/org/funding/comment/vo/enumType/CommentType.java
  backend_set/src/main/java/org/funding/fund/vo/ChallengeVO.java
  backend_set/src/main/java/org/funding/fund/vo/DepositVO.java
  backend_set/src/main/java/org/funding/fund/vo/DonationVO.java
  backend_set/src/main/java/org/funding/fund/vo/FinancialProductVO.java
  backend_set/src/main/java/org/funding/fund/vo/FundVO.java
  backend_set/src/main/java/org/funding/fund/vo/InstallmentVO.java
  backend_set/src/main/java/org/funding/fund/vo/enumType/FundType.java
  backend_set/src/main/java/org/funding/fund/vo/enumType/ProgressType.java
  backend_set/src/main/java/org/funding/mapping/RetryVotesVO.java
  backend_set/src/main/java/org/funding/mapping/UserBadgeVO.java
  backend_set/src/main/java/org/funding/mapping/VotesVO.java
  backend_set/src/main/java/org/funding/project/vo/ProjectVO.java
  backend_set/src/main/java/org/funding/project/vo/enumType/Feed.java
  backend_set/src/main/java/org/funding/user/vo/MemberVO.java
  backend_set/src/main/java/org/funding/user/vo/enumType/Role.java
Labels: feature

#10 feat: Spring legacy프로젝트 Swagger 적용
  backend_set/build.gradle
  backend_set/src/main/java/org/funding/config/ServletConfig.java
  backend_set/src/main/java/org/funding/config/SwaggerConfig.java
  backend_set/src/main/java/org/funding/config/WebConfig.java
  backend_set/src/main/java/org/funding/controller/HomeController.java
  backend_set/src/main/java/org/funding/controller/TestController.java
  backend_set/src/main/java/org/funding/security/config/SecurityConfig.java
  backend_set/src/main/java/org/funding/security/handler/CustomAuthenticationEntryPoint.java
  backend_set/src/main/webapp/WEB-INF/views/custom404.jsp
  backend_set/src/main/webapp/WEB-INF/views/error_page.jsp
  backend_set/src/main/webapp/WEB-INF/views/index.jsp
  backend_set/src/main/webapp/WEB-INF/views/security/admin.jsp
  backend_set/src/main/webapp/WEB-INF/views/security/all.jsp
  backend_set/src/main/webapp/WEB-INF/views/security/login.jsp
  backend_set/src/main/webapp/WEB-INF/views/security/logout.jsp
  backend_set/src/main/webapp/WEB-INF/views/security/member.jsp
Labels: feature

#15 Refactor#11 security login join 기능 검증 구현
  backend_set/.idea/dataSources.xml
  backend_set/.idea/mybatisx/templates.xml
  backend_set/.idea/sqldialects.xml
  backend_set/fund.sql
  backend_set/fund2.sql
  backend_set/src/main/java/org/funding/user/controller/MemberController.java
  backend_set/src/main/java/org/funding/user/dao/MemberDAO.java
  backend_set/src/main/java/org/funding/user/dto/MemberLoginDTO.java
  backend_set/src/main/java/org/funding/user/dto/MemberSignupDTO.java
  backend_set/src/main/java/org/funding/user/mapper/MemberMapper.xml
  backend_set/src/main/java/org/funding/user/service/MemberService.java
  backend_set/src/main/java/org/funding/user/vo/MemberVO.java
  backend_set/src/main/resources/org/funding/user/dao/MemberDAO.xml
Labels: refactor

#20 feat: 이메일 검증 로직 구현
  backend_set/build.gradle
  backend_set/src/main/java/org/funding/config/MailConfig.java
  backend_set/src/main/java/org/funding/config/RootConfig.java
  backend_set/src/main/java/org/funding/config/ServletConfig.java
  backend_set/src/main/java/org/funding/config/SwaggerConfig.java
  backend_set/src/main/java/org/funding/emailAuth/controller/EmailAuthController.java
  backend_set/src/main/java/org/funding/emailAuth/dao/EmailDAO.java
  backend_set/src/main/java/org/funding/emailAuth/service/EmailService.java
  backend_set/src/main/java/org/funding/emailAuth/vo/EmailAuthVO.java
  backend_set/src/main/java/org/funding/exception/CommonExceptionAdvice.java
  backend_set/src/main/java/org/funding/exception/GlobalExceptionHandler.java
  backend_set/src/main/java/org/funding/security/config/SecurityConfig.java
  backend_set/src/main/java/org/funding/user/dao/MemberDAO.java
  backend_set/src/main/java/org/funding/user/vo/MemberLoginVO.java
  backend_set/src/main/resources/org/funding/emailAuth/dao/EmailDAO.xml
Labels: feature

#27 Feat#12 fund
  backend_set/.idea/dataSources.xml
  backend_set/src/main/java/org/funding/config/RootConfig.java
  backend_set/src/main/java/org/funding/config/ServletConfig.java
  backend_set/src/main/java/org/funding/financialProduct/dao/ChallengeDAO.java
  backend_set/src/main/java/org/funding/financialProduct/dao/DonationDAO.java
  backend_set/src/main/java/org/funding/financialProduct/dao/FinancialProductDAO.java
  backend_set/src/main/java/org/funding/financialProduct/dao/LoanDAO.java
  backend_set/src/main/java/org/funding/financialProduct/dao/SavingsDAO.java
  backend_set/src/main/java/org/funding/financialProduct/dto/ChallengeDTO.java
  backend_set/src/main/java/org/funding/financialProduct/dto/DonationDTO.java
  backend_set/src/main/java/org/funding/financialProduct/dto/FinancialProductDTO.java
  backend_set/src/main/java/org/funding/financialProduct/dto/LoanDTO.java
  backend_set/src/main/java/org/funding/financialProduct/dto/SavingsDTO.java
  backend_set/src/main/java/org/funding/financialProduct/vo/ChallengeVO.java
  backend_set/src/main/java/org/funding/financialProduct/vo/DonationVO.java
  backend_set/src/main/java/org/funding/financialProduct/vo/FinancialProductVO.java
  backend_set/src/main/java/org/funding/financialProduct/vo/LoanVO.java
  backend_set/src/main/java/org/funding/financialProduct/vo/SavingsVO.java
  backend_set/src/main/java/org/funding/fund/controller/FundController.java
  backend_set/src/main/java/org/funding/fund/dao/FundDAO.java
  backend_set/src/main/java/org/funding/fund/dto/FundCreateDTO.java
  backend_set/src/main/java/org/funding/fund/dto/FundDTO.java
  backend_set/src/main/java/org/funding/fund/dto/FundProductRequestDTO.java
  backend_set/src/main/java/org/funding/fund/service/FundService.java
  backend_set/src/main/java/org/funding/fund/vo/ChallengeVO.java
  backend_set/src/main/java/org/funding/fund/vo/DepositVO.java
  backend_set/src/main/java/org/funding/fund/vo/DonationVO.java
  backend_set/src/main/java/org/funding/fund/vo/FinancialProductVO.java
  backend_set/src/main/java/org/funding/fund/vo/FundVO.java
  backend_set/src/main/java/org/funding/fund/vo/InstallmentVO.java
  backend_set/src/main/java/org/funding/fund/vo/enumType/FundType.java
  backend_set/src/main/java/org/funding/security/config/SecurityConfig.java
  backend_set/src/main/resources/application.properties
  backend_set/src/main/resources/org/funding/financialProduct/dao/ChallengeDAO.xml
  backend_set/src/main/resources/org/funding/financialProduct/dao/DonationDAO.xml
  backend_set/src/main/resources/org/funding/financialProduct/dao/FinancialProductDAO.xml
  backend_set/src/main/resources/org/funding/financialProduct/dao/LoanDAO.xml
  backend_set/src/main/resources/org/funding/financialProduct/dao/SavingsDAO.xml
  backend_set/src/main/resources/org/funding/fund.dao/FundDAO.xml
Labels: feature

#29 test: 로그인, 회원가입 테스트 코드 작성
  backend_set/build.gradle
  backend_set/src/main/java/org/funding/user/controller/MemberController.java
  backend_set/src/main/resources/application.properties
  backend_set/src/test/java/org/funding/config/RootConfigTest.java
  backend_set/src/test/java/org/funding/persistence/JDBCTests.java
  backend_set/src/test/java/org/funding/user/controller/MemberControllerTest.java
Labels: test

#36 feat: 스케줄러를 통한 펀딩 자동 종료 기능 구현
  backend_set/src/main/java/org/funding/fund/controller/FundController.java
  backend_set/src/main/java/org/funding/fund/dao/FundDAO.java
  backend_set/src/main/java/org/funding/fund/scheduler/FundScheduler.java
  backend_set/src/main/java/org/funding/fund/service/FundService.java
Labels: feature

#38 Feat#37 펀딩상품 ai summary
  backend_set/src/main/java/org/funding/fund/vo/enumType/FundType.java
  backend_set/src/main/java/org/funding/openAi/client/OpenAIClient.java
  backend_set/src/main/java/org/funding/openAi/controller/OpenAiController.java
  backend_set/src/main/java/org/funding/openAi/dto/SummaryFundRequestDTO.java
  backend_set/src/main/java/org/funding/openAi/dto/SummaryFundResponseDTO.java
  backend_set/src/main/java/org/funding/openAi/service/ChatService.java
  backend_set/src/main/java/org/funding/security/config/SecurityConfig.java
Labels: feature

#45 feat: 펀딩 추천 ai 기능 구현
  backend_set/src/main/java/org/funding/openAi/controller/OpenAiController.java
  backend_set/src/main/java/org/funding/openAi/dao/FundAIDAO.java
  backend_set/src/main/java/org/funding/openAi/service/FundAIService.java
  backend_set/src/main/java/org/funding/security/config/SecurityConfig.java
  backend_set/src/main/resources/org/funding/openAi/dao/FundAIDAO.xml
Labels: feature

#51 feat : 펀딩 수정, 삭제 기능 구현
  backend_set/src/main/java/org/funding/financialProduct/dao/ChallengeDAO.java
  backend_set/src/main/java/org/funding/financialProduct/dao/DonationDAO.java
  backend_set/src/main/java/org/funding/financialProduct/dao/FinancialProductDAO.java
  backend_set/src/main/java/org/funding/financialProduct/dao/LoanDAO.java
  backend_set/src/main/java/org/funding/financialProduct/dao/SavingsDAO.java
  backend_set/src/main/java/org/funding/fund/controller/FundController.java
  backend_set/src/main/java/org/funding/fund/dao/FundDAO.java
  backend_set/src/main/java/org/funding/fund/dto/FundUpdateRequestDTO.java
  backend_set/src/main/java/org/funding/fund/service/FundService.java
  backend_set/src/main/java/org/funding/security/config/SecurityConfig.java
  backend_set/src/main/resources/org/funding/financialProduct/dao/ChallengeDAO.xml
  backend_set/src/main/resources/org/funding/financialProduct/dao/DonationDAO.xml
  backend_set/src/main/resources/org/funding/financialProduct/dao/LoanDAO.xml
  backend_set/src/main/resources/org/funding/financialProduct/dao/SavingsDAO.xml
  backend_set/src/main/resources/org/funding/fund/dao/FundDAO.xml
Labels: feature

#53 Feat#46 재출시 투표 기능 구현
  backend_set/src/main/java/org/funding/config/RootConfig.java
  backend_set/src/main/java/org/funding/config/ServletConfig.java
  backend_set/src/main/java/org/funding/fund/controller/FundController.java
  backend_set/src/main/java/org/funding/fund/dto/FundDetailResponseDTO.java
  backend_set/src/main/java/org/funding/fund/dto/FundListResponseDTO.java
  backend_set/src/main/java/org/funding/fund/vo/FundVO.java
  backend_set/src/main/java/org/funding/retryVotes/controller/RetryVotesController.java
  backend_set/src/main/java/org/funding/retryVotes/dao/RetryVotesDAO.java
  backend_set/src/main/java/org/funding/retryVotes/dto/DoVoteRequestDTO.java
  backend_set/src/main/java/org/funding/retryVotes/service/RetryVotesService.java
  backend_set/src/main/java/org/funding/security/config/SecurityConfig.java
  backend_set/src/main/resources/org/funding/fund/dao/FundDAO.xml
  backend_set/src/main/resources/org/funding/openAi/dao/FundAIDAO.xml
  backend_set/src/main/resources/org/funding/retryVotes/dao/RetryVotesDAO.xml
  backend_set/src/main/resources/org/funding/user/dao/MemberDAO.xml
Labels: feature

#58 Feat#54 ai image analyze 기능 구현
  backend_set/src/main/java/org/funding/config/RootConfig.java
  backend_set/src/main/java/org/funding/financialProduct/vo/ChallengeVO.java
  backend_set/src/main/java/org/funding/fund/dto/FundProductRequestDTO.java
  backend_set/src/main/java/org/funding/fund/service/FundService.java
  backend_set/src/main/java/org/funding/openAi/client/OpenAIVisionClient.java
  backend_set/src/main/java/org/funding/openAi/controller/OpenAiController.java
  backend_set/src/main/java/org/funding/openAi/service/OpenVisionService.java
  backend_set/src/main/java/org/funding/security/config/SecurityConfig.java
  backend_set/src/main/resources/org/funding/financialProduct/dao/ChallengeDAO.xml
Labels: feature

#62 refactor: voteDAO 수정
  backend_set/.idea/sqldialects.xml
  backend_set/src/main/java/org/funding/votes/dao/VotesDAO.java
  backend_set/src/main/resources/org/funding/mapping/dao/VotesDAO.xml
  backend_set/src/main/resources/org/funding/votes/dao/VotesDAO.xml
Labels: feature

#70 Feat#68 [금융 상품] 대출 기부 가입, 관리 기능 구현
  backend_set/src/main/java/org/funding/userDonation/controller/UserDonationController.java
  backend_set/src/main/java/org/funding/userDonation/dao/UserDonationDAO.java
  backend_set/src/main/java/org/funding/userDonation/dto/DonateRequestDTO.java
  backend_set/src/main/java/org/funding/userDonation/dto/DonateResponseDTO.java
  backend_set/src/main/java/org/funding/userDonation/service/UserDonationService.java
  backend_set/src/main/java/org/funding/userDonation/vo/UserDonationVO.java
  backend_set/src/main/java/org/funding/userLoan/controller/UserLoanController.java
  backend_set/src/main/java/org/funding/userLoan/dao/UserLoanDAO.java
  backend_set/src/main/java/org/funding/userLoan/dto/ApproveUserLoanRequestDTO.java
  backend_set/src/main/java/org/funding/userLoan/dto/CancelLoanRequestDTO.java
  backend_set/src/main/java/org/funding/userLoan/dto/UserLoanRequestDTO.java
  backend_set/src/main/java/org/funding/userLoan/dto/UserLoanResponseDTO.java
  backend_set/src/main/java/org/funding/userLoan/service/UserLoanService.java
  backend_set/src/main/java/org/funding/userLoan/vo/UserLoanVO.java
  backend_set/src/main/java/org/funding/userLoan/vo/enumType/SuccessType.java
  backend_set/src/main/resources/org/funding/userDonation/dao/UserDonationDAO.xml
  backend_set/src/main/resources/org/funding/userLoan/dao/UserLoanDAO.xml
Labels: feature

#80 feat: docker file 추가, jar 설정
  backend_set/.idea/dataSources.xml
  backend_set/Dockerfile
  backend_set/build.gradle
  backend_set/src/main/java/org/funding/fund/dto/FundListResponseDTO.java
  backend_set/src/main/java/org/funding/userSaving/service/UserSavingService.java
Labels: feature

#82 refactor: gradlew파일 수정
  backend_set/gradle/wrapper/gradle-wrapper.jar
  backend_set/gradle/wrapper/gradle-wrapper.properties
  backend_set/gradlew
  backend_set/gradlew.bat
Labels: feature

#85 refactor: docker 파일 수정
  backend_set/Dockerfile
Labels: refactor

#87 refactor: war 수정
  backend_set/Dockerfile
Labels: refactor

#91 feat: 헬스체커 api 등록
  backend_set/.idea/dataSources.xml
  backend_set/src/main/java/org/funding/healthChecker/controller/HealthCheckerController.java
  backend_set/src/main/java/org/funding/security/config/SecurityConfig.java
Labels: feature

#92 refactor: servlet config에 헬스체커 컨트롤러 추가
  backend_set/src/main/java/org/funding/config/ServletConfig.java
Labels: refactor

#93 refactor: response entity 추가
  backend_set/src/main/java/org/funding/healthChecker/controller/HealthCheckerController.java
Labels: refactor

#96 refactor: docker file
  backend_set/Dockerfile
  backend_set/build.gradle
  backend_set/src/test/java/org/funding/config/RootConfigTest.java
  backend_set/src/test/java/org/funding/persistence/JDBCTests.java
  backend_set/src/test/java/org/funding/security/PasswordEncoderTest.java
  backend_set/src/test/java/org/funding/security/account/mapper/UserDetailsMapperTest.java
  backend_set/src/test/java/org/funding/security/util/JwtProcessorTest.java
  backend_set/src/test/java/org/funding/user/controller/MemberControllerTest.java
Labels: refactor
